apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lemuria.fullname" . }}-config
  labels:
    {{- include "lemuria.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  lemuria.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
