{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemuria.fullname" . }}
  labels:
    {{- include "lemuria.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | b64enc | quote }}
  GITHUB_APP_ID: {{ .Values.secrets.githubAppId | b64enc | quote }}
  GITHUB_APP_PRIVATE_KEY: {{ .Values.secrets.githubAppPrivateKey | b64enc | quote }}
  ARGOCD_TOKEN: {{ .Values.secrets.argocdToken | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
{{- end }}
