{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemuria.fullname" . }}-secrets
  labels:
    {{- include "lemuria.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  secrets.yaml: |
    {{- toYaml .Values.secrets.config | nindent 4 }}
{{- end }}
